name: Main

on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
    - master
    paths-ignore:
      - 'Packages/**'
      - 'ProjectSettings/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.ps1'
  
jobs:
  RunUnityTests:
    name: Run Unity Tests
    uses: ./.github/workflows/RunUnityTests.yml
    secrets: inherit

  #SonarQube:
  #  name: SonarQube Analysis
  #  needs: RunUnityTests
  #  uses: ./.github/workflows/SonarQube.yml
  #  secrets: inherit

  Release:
    name: Semantic Release
    needs: RunUnityTests
    uses: ./.github/workflows/Semantic.yml
    secrets: inherit
